import "./globals.css";
import { NextUiProvider } from "@/context/NextUiProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NextUiProvider>{children}</NextUiProvider>
      </body>
    </html>
  );
}
