import Header from "@/components/header";
import "./globals.css";
import { NextUiProvider } from "@/context/NextUiProvider";
import { Source_Sans_3 } from "next/font/google";
const sourceSans = Source_Sans_3({
  subsets: ["latin"],
  weights: ["400", "600", "900"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${sourceSans.className}`}>
        <Header />
        <NextUiProvider>{children}</NextUiProvider>
      </body>
    </html>
  );
}
